/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Models.NhanVien;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import ql_cafe.ConnectDB;
import static ql_cafe.ConnectDB.getConnection;


/**
 *
 * @author Thang Mi
 */

public class AddNhanVien extends javax.swing.JFrame {
     private static final Charset UTF_8 = StandardCharsets.UTF_8;
    private static final String OUTPUT_FORMAT = "%-20s:%s"; 
    public AddNhanVien() throws SQLException {
        initComponents();
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNV = new javax.swing.JPanel();
        TenBenhNhan = new javax.swing.JLabel();
        TriGiaLuong = new javax.swing.JLabel();
        DC = new javax.swing.JLabel();
        DT = new javax.swing.JLabel();
        GT = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTRiGiaLuong = new javax.swing.JTextField();
        txtGT = new javax.swing.JComboBox<>();
        Thêm = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DT1 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        CMND = new javax.swing.JLabel();
        txtNS = new com.toedter.calendar.JDateChooser();
        txtNBD = new com.toedter.calendar.JDateChooser();
        Thoát = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        NS1 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        MaNV = new javax.swing.JLabel();
        DT3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addNV.setBackground(new java.awt.Color(91, 48, 91));
        addNV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TenBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TenBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        TenBenhNhan.setText("Tên nhân viên");
        addNV.add(TenBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 120, -1, -1));

        TriGiaLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TriGiaLuong.setForeground(new java.awt.Color(255, 255, 255));
        TriGiaLuong.setText("Trị Giá Lương");
        addNV.add(TriGiaLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        DC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DC.setForeground(new java.awt.Color(255, 255, 255));
        DC.setText("Ngày Bắt Đầu :");
        addNV.add(DC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        DT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DT.setForeground(new java.awt.Color(255, 255, 255));
        DT.setText("Email :");
        addNV.add(DT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        GT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GT.setForeground(new java.awt.Color(255, 255, 255));
        GT.setText("Giới Tính :");
        addNV.add(GT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        addNV.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 202, 27));

        txtTRiGiaLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTRiGiaLuongActionPerformed(evt);
            }
        });
        addNV.add(txtTRiGiaLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 202, 27));

        txtGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        txtGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGTActionPerformed(evt);
            }
        });
        addNV.add(txtGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 101, 30));

        Thêm.setBackground(new java.awt.Color(61, 29, 61));
        Thêm.setForeground(new java.awt.Color(255, 255, 255));
        Thêm.setText("Thêm");
        Thêm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThêmActionPerformed(evt);
            }
        });
        addNV.add(Thêm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 94, 39));

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });
        addNV.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 202, 27));

        jPanel2.setBackground(new java.awt.Color(61, 29, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        addNV.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, 610, -1));

        DT1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DT1.setForeground(new java.awt.Color(255, 255, 255));
        DT1.setText("Điện thoại :");
        addNV.add(DT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });
        addNV.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 202, 27));

        CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CMND.setForeground(new java.awt.Color(255, 255, 255));
        CMND.setText("CMND :");
        addNV.add(CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));
        addNV.add(txtNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 30));

        txtNBD.setDateFormatString("yyyy-MM-dd");
        addNV.add(txtNBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, 30));

        Thoát.setBackground(new java.awt.Color(61, 29, 61));
        Thoát.setForeground(new java.awt.Color(255, 255, 255));
        Thoát.setText("Thoát");
        Thoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoátActionPerformed(evt);
            }
        });
        addNV.add(Thoát, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 94, 39));

        Reset.setBackground(new java.awt.Color(61, 29, 61));
        Reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset");
        Reset.setMaximumSize(new java.awt.Dimension(59, 23));
        Reset.setMinimumSize(new java.awt.Dimension(59, 23));
        Reset.setPreferredSize(new java.awt.Dimension(59, 23));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        addNV.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 100, 40));

        NS1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NS1.setForeground(new java.awt.Color(255, 255, 255));
        NS1.setText("Ngày sinh :");
        addNV.add(NS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, -1));

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        addNV.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 202, 27));

        MaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MaNV.setForeground(new java.awt.Color(255, 255, 255));
        MaNV.setText("MaNV:");
        addNV.add(MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        DT3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DT3.setForeground(new java.awt.Color(255, 255, 255));
        DT3.setText("Email :");
        addNV.add(DT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        addNV.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 202, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNV, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNV, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTRiGiaLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTRiGiaLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTRiGiaLuongActionPerformed

    private void ThêmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThêmActionPerformed
//        // TODO add your handling code here:
final DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    if (txtTRiGiaLuong.getText().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
     if (txtSDT.getText().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
      if (txtCMND.getText().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
       if (txtTenNV.getText().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
        if (txtGT.getSelectedItem().toString().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
         if (txtNS.getDateFormatString().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    } if (txtNBD.getDateFormatString().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
          if (txtEmail.getText().isBlank())
    {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin","Enor",JOptionPane.INFORMATION_MESSAGE);
    }
   
       try {
            // connnect to database 'testdb'
            Connection conn =(Connection) getConnection(ConnectDB.DB_URL, ConnectDB.USER_NAME, ConnectDB.PASSWORD);
            // crate statement
            Statement sts = (Statement) conn.createStatement();
            // get data from table 'student'
  sts.executeUpdate("INSERT INTO `nhanvien`(`HoTenNV`, `NgaySinhNV`, `GioiTinhNV`, `SdtNV`,`CMNDNV` `EmailNV`, `NgayBatDauNV`, `MaNV`,`TRiGIaLuongNV`) VALUES (NULL,'"+txtTenNV+"','"+df.format(txtNS.getDate())+"','"+txtGT.getSelectedItem()+"','"+txtSDT.getText()+"', '"+txtCMND.getText()+"',"+txtEmail.getText()+"','"+df.format(txtNS.getDate())+"','"+txtMaNV.getText()+"','"+txtTRiGiaLuong.getText()+"');");
            // close connection
            conn.close();
       }
       catch(Exception ex)
        {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_ThêmActionPerformed

    private void txtGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGTActionPerformed

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void ThoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoátActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_ThoátActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        
        txtTenNV.setText("");
        txtNS.setDateFormatString("");
        txtGT.getSelectedItem().toString();
        txtCMND.setText("");
        txtTRiGiaLuong.setText("");
        txtEmail.setText("");
        txtNBD.setDateFormatString("");
    }//GEN-LAST:event_ResetActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinLuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinLuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinLuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemThongTinLuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddNhanVien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void NewScreen() {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddNhanVien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMND;
    private javax.swing.JLabel DC;
    private javax.swing.JLabel DT;
    private javax.swing.JLabel DT1;
    private javax.swing.JLabel DT3;
    private javax.swing.JLabel GT;
    private javax.swing.JLabel MaNV;
    private javax.swing.JLabel NS1;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel TenBenhNhan;
    private javax.swing.JButton Thoát;
    private javax.swing.JButton Thêm;
    private javax.swing.JLabel TriGiaLuong;
    private javax.swing.JPanel addNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGT;
    private javax.swing.JTextField txtMaNV;
    private com.toedter.calendar.JDateChooser txtNBD;
    private com.toedter.calendar.JDateChooser txtNS;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTRiGiaLuong;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

    private Object connectDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
