/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORM;

import Models.HoaDon;
import Models.KhachHang;
import Models.Luong;
import Models.NhanVien;
import com.mysql.jdbc.Statement;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Panel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ql_cafe.ConnectDB;

/**
 *
 * @author ADMIN
 */
public class Staff extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();


    /**
     * Creates new form MENU
     */
    public void TaoTableHoaDon() throws SQLException{
        //lấy dữ liệu từ mysql
        Connection con = new ConnectDB().dbConnector();
        ArrayList<HoaDon> list = new ArrayList();
        String sqlString = "Select * from hoadon";
        Statement start = (Statement) con.createStatement();
        ResultSet rs = start.executeQuery(sqlString);
        while(rs.next()){
        HoaDon hd = new HoaDon();
            hd.setMaNV(rs.getString("manv"));
            hd.setMaHD(rs.getString("mahd"));
            hd.setMaSP(rs.getString("masp"));
            hd.setSL(rs.getString("soluong"));
            hd.setDG(rs.getString("dongia"));
            hd.setMaKH(rs.getString("makh"));
            hd.setLoaiKH(rs.getString("loaikh"));
            hd.setDiscount(rs.getString("discount"));
            hd.setThoiGian(rs.getDate("thoigian"));
            hd.setThanhTien(rs.getString("thanhtien"));
            list.add(hd);
            System.out.println(hd);
        }
        rs.close();
        start.close();
        con.close();
        //
        DefaultTableModel tblModelTT = new DefaultTableModel();
        //tblModelTT = (DefaultTableModel) tbHoaDon.getModel();
        for(var x: list)
            tblModelTT.addRow(new Object[] {x.getMaNV(), x.getMaHD(), x.getMaSP(), x.getSL(), x.getDG(), x.getMaKH(), x.getLoaiKH(), x.getDiscount(), x.getThoiGian(), x.getThanhTien()} );
    };
    public void TaoTableNhanVien() throws SQLException{
        //lấy dữ liệu từ mysql
        Connection con = new ConnectDB().dbConnector();
        ArrayList<Luong> list = new ArrayList();
        String sqlString = "Select * from luong";
        Statement start = (Statement) con.createStatement();
        ResultSet rs = start.executeQuery(sqlString);
        while(rs.next()){
        Luong luong = new Luong();
            luong.setMaNV(rs.getString("manv"));
            luong.setTenNV(rs.getString("tennv"));
            luong.setGioLamViec(rs.getString("giolamviec"));
            luong.setLuong(rs.getString("luong"));
            list.add(luong);
            System.out.println(luong);
        }
        rs.close();
        start.close();
        con.close();
        //
        DefaultTableModel tblModelTT = new DefaultTableModel();
       // tblModelTT = (DefaultTableModel) tbNV.getModel();
        for(var x: list)
            tblModelTT.addRow(new Object[] {x.getMaNV(), x.getTenNV(), x.getGioLamViec(), x.getLuong()} );
    };
    public Staff() throws SQLException {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        TaoTableNhanVien();
        TaoTableHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton21 = new javax.swing.JButton();
        Staff = new javax.swing.JPanel();
        function = new javax.swing.JPanel();
        HomeFun = new javax.swing.JButton();
        MenuFun = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Head = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        control = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();

        jButton21.setText("jButton21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Staff.setBackground(new java.awt.Color(204, 255, 204));
        Staff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        function.setBackground(new java.awt.Color(51, 0, 51));
        function.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeFun.setBackground(new java.awt.Color(61, 29, 61));
        HomeFun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HomeFun.setForeground(new java.awt.Color(255, 255, 255));
        HomeFun.setText("Home");
        HomeFun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserFunMouseClicked(evt);
            }
        });
        HomeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeFunActionPerformed(evt);
            }
        });
        function.add(HomeFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 70));

        MenuFun.setBackground(new java.awt.Color(61, 29, 61));
        MenuFun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuFun.setForeground(new java.awt.Color(255, 255, 255));
        MenuFun.setText("Menu");
        MenuFun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserFunMouseClicked(evt);
            }
        });
        MenuFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFunActionPerformed(evt);
            }
        });
        function.add(MenuFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        function.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 60));

        Staff.add(function, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 470));

        Head.setBackground(new java.awt.Color(66, 48, 86));

        jLabel3.setFont(new java.awt.Font("Vladimir Script", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("T TEAM   ");

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Permission : Staff");

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        Staff.add(Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 780, 70));

        control.setBackground(new java.awt.Color(102, 0, 0));
        control.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(66, 48, 86));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 255, 255));
        welcome.setText("WELCOME");
        Home.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, 290, 80));

        picture.setMaximumSize(new java.awt.Dimension(640, 500));
        picture.setPreferredSize(new java.awt.Dimension(680, 401));
        Home.add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 640, -1));

        control.add(Home, "card5");

        Menu.setBackground(new java.awt.Color(0, 153, 153));
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DRINK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 12, 5));

        jButton1.setBackground(new java.awt.Color(153, 223, 223));
        jButton1.setText("...");
        jPanel2.add(jButton1);

        jButton8.setBackground(new java.awt.Color(153, 223, 223));
        jButton8.setText("...");
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(153, 223, 223));
        jButton9.setText("...");
        jPanel2.add(jButton9);

        jButton10.setBackground(new java.awt.Color(153, 223, 223));
        jButton10.setText("...");
        jPanel2.add(jButton10);

        jButton2.setBackground(new java.awt.Color(153, 223, 223));
        jButton2.setText("...");
        jPanel2.add(jButton2);

        jButton20.setBackground(new java.awt.Color(153, 223, 223));
        jButton20.setText("...");
        jPanel2.add(jButton20);

        jButton19.setBackground(new java.awt.Color(153, 223, 223));
        jButton19.setText("...");
        jPanel2.add(jButton19);

        jButton13.setBackground(new java.awt.Color(153, 223, 223));
        jButton13.setText("...");
        jPanel2.add(jButton13);

        jButton14.setBackground(new java.awt.Color(153, 223, 223));
        jButton14.setText("...");
        jPanel2.add(jButton14);

        jButton17.setBackground(new java.awt.Color(153, 223, 223));
        jButton17.setText("...");
        jPanel2.add(jButton17);

        jButton23.setBackground(new java.awt.Color(153, 223, 223));
        jButton23.setText("...");
        jPanel2.add(jButton23);

        jButton24.setBackground(new java.awt.Color(153, 223, 223));
        jButton24.setText("...");
        jPanel2.add(jButton24);

        jButton22.setBackground(new java.awt.Color(153, 223, 223));
        jButton22.setText("...");
        jPanel2.add(jButton22);

        jButton18.setBackground(new java.awt.Color(153, 223, 223));
        jButton18.setText("...");
        jPanel2.add(jButton18);

        jButton16.setBackground(new java.awt.Color(153, 223, 223));
        jButton16.setText("...");
        jPanel2.add(jButton16);

        jButton15.setBackground(new java.awt.Color(153, 223, 223));
        jButton15.setText("...");
        jPanel2.add(jButton15);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Table");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new java.awt.GridLayout(3, 3, 1, 4));

        jButton25.setBackground(new java.awt.Color(153, 223, 223));
        jButton25.setText("1");
        jPanel4.add(jButton25);

        jButton26.setBackground(new java.awt.Color(153, 223, 223));
        jButton26.setText("2");
        jPanel4.add(jButton26);

        jButton28.setBackground(new java.awt.Color(153, 223, 223));
        jButton28.setText("3");
        jPanel4.add(jButton28);

        jButton31.setBackground(new java.awt.Color(153, 223, 223));
        jButton31.setText("4");
        jPanel4.add(jButton31);

        jButton27.setBackground(new java.awt.Color(153, 223, 223));
        jButton27.setText("5");
        jPanel4.add(jButton27);

        jButton30.setBackground(new java.awt.Color(153, 223, 223));
        jButton30.setText("6");
        jPanel4.add(jButton30);

        jButton29.setBackground(new java.awt.Color(153, 223, 223));
        jButton29.setText("7");
        jPanel4.add(jButton29);

        jButton32.setBackground(new java.awt.Color(153, 223, 223));
        jButton32.setText("8");
        jPanel4.add(jButton32);

        jButton33.setBackground(new java.awt.Color(153, 223, 223));
        jButton33.setText("9");
        jPanel4.add(jButton33);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 3, 13)); // NOI18N
        jLabel6.setText("CUSTOMER:");

        jComboBox3.setBackground(new java.awt.Color(153, 223, 223));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "NOR" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(153, 223, 223));
        jTable2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "QUANTITY", "DISCOUNT", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jScrollPane2.setViewportView(jTable2);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 10)); // NOI18N
        jLabel7.setText("TOTAL PRICE:");

        jTextField3.setBackground(new java.awt.Color(153, 223, 223));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(26, 163, 163));
        jButton34.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jButton34.setText("PRINT");

        jButton35.setBackground(new java.awt.Color(26, 163, 163));
        jButton35.setFont(new java.awt.Font("Castellar", 1, 13)); // NOI18N
        jButton35.setText("CANCEL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Search :");

        jLabel20.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Search :");

        jTextField9.setBackground(new java.awt.Color(153, 223, 223));
        jTextField9.setForeground(new java.awt.Color(51, 51, 51));

        jButton41.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuLayout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton41))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(jLabel19)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        control.add(Menu, "card4");

        Staff.add(control, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 750, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void HomeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeFunActionPerformed

    private void MenuFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFunActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void UserFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFunMouseClicked
        // TODO add your handling code here:
        if (evt.getSource()==MenuFun){
            Menu.setVisible(true);
           // BILLS.setVisible(false);
          //  User.setVisible(false);
            Home.setVisible(false);
        }
       
       
        if (evt.getSource()==HomeFun){
            Menu.setVisible(false);
          //  BILLS.setVisible(false);
          //  User.setVisible(false);
            Home.setVisible(true);
        }
    }//GEN-LAST:event_UserFunMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Staff().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Staff.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private javax.swing.JPanel Home;
    private javax.swing.JButton HomeFun;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton MenuFun;
    private javax.swing.JPanel Staff;
    private javax.swing.JPanel control;
    private javax.swing.JPanel function;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
